//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.27 at 03:13:16 PM CEST 
//


package com.usi;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for question complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="question">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="choice" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="4" minOccurs="4"/>
 *       &lt;/sequence>
 *       &lt;attribute name="goodchoice" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "question", propOrder = {
        "label",
        "choice"
})
public class Question implements Serializable {

    @XmlElement(required = true)
    protected String label;
    @XmlElement(required = true)
    protected List<String> choice;
    @XmlAttribute(name = "goodchoice", required = true)
    protected int goodchoice;
@XmlTransient
    private byte[] goodAnswerCache = null;

    /**
     * Gets the value of the label property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the choice property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the choice property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChoice().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     */
    public List<String> getChoice() {
        if (choice == null) {
            choice = new ArrayList<String>();
        }
        return this.choice;
    }

    /**
     * Gets the value of the goodchoice property.
     */
    public int getGoodchoice() {
        return goodchoice;
    }

    /**
     * Sets the value of the goodchoice property.
     */
    public void setGoodchoice(int value) {
        this.goodchoice = value;
    }

    public byte[] getGoodAnswer() {
        if (goodAnswerCache == null) {
            goodAnswerCache = getChoice().get(getGoodchoice()-1).getBytes();
        }
        return goodAnswerCache;
    }
}
